---
title: "Exercise SQL Part2"
author: "Johnny Chiu"
date: "2017/9/12"
output: html_document
---

# SQL Part 2: Exercises

question: <https://github.com/nuitrcs/databases_workshop/blob/master/sql/part2_exercises.md>  
solution: <https://github.com/nuitrcs/databases_workshop/blob/master/sql/part2_exercises_with_answers.md>


# Setup
```{r}
library(RPostgreSQL)
con <- dbConnect(dbDriver("PostgreSQL"), host="pg", dbname="dvdrental") 
# list all the table
dbListTables(con)
```


There may be other ways to achieve the same result.  Remember that SQL commands are not case sensitive (but data values are).

All of these exercises use the `dvdrental` database.  

Exercises often use multiple commands or aspects of SQL, but they are titled/grouped by their focus.


## Exercise: Subqueries

What films are actors with ids 129 and 195 in together?
* a bad answer
```{sql, connection=con}
select * from (select foo.film_id, count(*) as co from
(select film_id, actor_id from film_actor where actor_id in (129,195)) as foo 
group by foo.film_id) as foo2 where co=2;
```
* answer:
```{sql, connection=con}
SELECT film_id FROM film_actor
WHERE actor_id=129
AND film_id IN (SELECT film_id FROM film_actor WHERE actor_id=195);
```



Challenge: How many actors are in more films than actor id 47?  Hint: this takes 2 subqueries (one nested in the other).  Work inside out: 1) how many films is actor 47 in; 2) which actors are in more films than this? 3) Count those actors.
```{sql, connection=con}
select count(distinct actor_id) from (
  select actor_id, count(distinct film_id) as unique_film_count from film_actor group by actor_id
  having count(distinct film_id) > (select count(distinct film_id) from film_actor where actor_id=47)
) as foo;
-- You can also use a subquery to select from another result set. In such cases, you have to give the subquery a name.
```


## Exercise: Joining Customers, Payments, and Staff

Join the customer and payment tables together with an inner join; select customer id, name, amount, and date and order by customer id.  Then join the staff table to them as well to add the staff's name.  
```{sql, connection=con}
select 
  c.customer_id, 
  first_name, 
  last_name, 
  amount, 
  payment_date 
from customer as c
inner join payment as p on c.customer_id=p.customer_id
order by c.customer_id;
```

```{sql, connection=con}
select 
  c.customer_id, 
  c.first_name, 
  c.last_name, 
  p.amount, 
  p.payment_date,
  p.staff_id,
  s.first_name staff_first_name,
  s.last_name staff_last_name
from customer as c
inner join payment as p on c.customer_id=p.customer_id
inner join staff as s on p.staff_id = s.staff_id
order by c.customer_id;
```


## Exercise: Joining for Better Addresses

Create a list of addresses that includes the name of the city instead of an ID number and the name of the country as well.   

```{sql, connection=con}
select 
  address,
  address2,
  a.city_id,
  ci.city,
  ci.country_id,
  co.country
from address as a
inner join city as ci on a.city_id=ci.city_id
inner join country as co on ci.country_id=co.country_id;
```
Another solution
```{sql connection=con}
SELECT address, address2, district, postal_code, city, country 
FROM address, city, country
WHERE address.city_id=city.city_id 
AND city.country_id = country.country_id;
```



## Exercise: Joining and Grouping

Repeating an exercise from Part 1, but adding in information from additional tables:  Which film (_by title_) has the most actors?  Which actor (_by name_) is in the most films?

```{sql, connection=con}
select film_id, title, count(*) from (
  select 
    f.film_id,
    f.title,
    fa.actor_id
  from film as f
  inner join film_actor as fa on f.film_id=fa.film_id
  order by film_id
) as tbl1 
group by film_id, title
order by count desc
limit 1;

```

Another solution(Better)
```{sql, connection=con}
SELECT title, count(actor_id) 
FROM film, film_actor
WHERE film.film_id=film_actor.film_id
GROUP BY title
ORDER BY count(actor_id) DESC 
LIMIT 1;
```


```{sql, connection=con}
select 
  full_name,
  count(*)
from (
  select 
    fa.actor_id,
    fa.film_id,
    concat(a.first_name,' ',a.last_name) full_name
  from film_actor as fa
  inner join actor as a on fa.actor_id=a.actor_id
) as tbl1
group by full_name
order by count desc
limit 1;
-- Susan Davis has two actor_id.
```

Another solution(Better)
```{sql, connection=con}
select 
  concat(a.first_name,' ',a.last_name) full_name,
  count(film_id)
from actor as a, film_actor as fa
where a.actor_id=fa.actor_id
group by full_name
order by count(film_id) desc;

```


Challenge: Which two actors have been in the most films together?  Hint: You can join a table to itself by including it twice with different aliases.  Hint 2: Try writing the query first to find the answer in terms of actor ids (not names); then for a super challenge (it takes a complicated query), rewrite it to get the actor names instead of the IDs.  Hint 3: make sure not to count pairs twice (a in the movie with b and b in the movie with a) and avoid counting cases of an actor being in a movie with themselves.

Provided answer for chanllenge:
```{sql, connection=con}
SELECT a.actor_id as actor_id_1, b.actor_id as actor_id_2, count(*)
FROM film_actor a, film_actor b -- join the table to itself
WHERE a.film_id=b.film_id -- on the film id
      AND a.actor_id > b.actor_id -- avoid duplicates and matching to the same actor
GROUP BY actor_id_1, actor_id_2
ORDER BY count(*) DESC ;
--LIMIT 1;
```

My solution for super challenge:
```{sql, connection=con}
select 
  c.first_name,
  c.last_name,
  d.first_name,
  d.last_name,
  fcount
from (
  SELECT a.actor_id as actor_id_1, b.actor_id as actor_id_2, count(*) as fcount
  FROM film_actor a, film_actor b -- join the table to itself
  WHERE a.film_id=b.film_id -- on the film id
        AND a.actor_id > b.actor_id -- avoid duplicates and matching to the same actor
  GROUP BY actor_id_1, actor_id_2
) as tbl1
inner join actor as c on c.actor_id=actor_id_1
inner join actor as d on d.actor_id=actor_id_2
order by fcount desc;

```


Provided answer for super challenge:
```{sql, connection=con}
SELECT c.first_name, c.last_name, d.first_name, d.last_name, fcount
FROM (
  SELECT a.actor_id AS a1, b.actor_id AS a2, count(*) AS fcount
  FROM film_actor a, film_actor b -- join the table to itself
  WHERE a.film_id=b.film_id -- on the film id
        AND a.actor_id > b.actor_id -- avoid duplicates and matching to the same actor
  GROUP BY a.actor_id, b.actor_id) as foo -- this is the query from above
INNER JOIN actor c ON c.actor_id=a1
INNER JOIN actor d ON d.actor_id=a2
ORDER BY fcount DESC LIMIT 1;
```



## Exercise: Joining and Grouping 2

Get a list of the names of customers who have spent more than $150, along with their total spending.
```{sql, connection=con}
select 
  c.first_name,
  c.last_name,
  sum(amount)
from customer as c, payment as p
where c.customer_id=p.customer_id
group by first_name, last_name
having sum(amount)>150
order by sum(amount) desc;
```
Another solution:
```{sql, connection=con}
SELECT first_name, last_name, sum(amount)
FROM customer c INNER JOIN payment p
ON c.customer_id=p.customer_id
GROUP BY first_name, last_name
HAVING sum(amount) > 150;
```



Who is the customer with the highest average payment amount?
```{sql, connection=con}
select 
  c.first_name,
  c.last_name,
  avg(amount)
from customer as c, payment as p
where c.customer_id=p.customer_id
group by first_name, last_name
order by avg(amount) desc
limit 1;

```

```{sql, connection=con}
SELECT c.customer_id, first_name, last_name, avg(amount)
FROM customer c INNER JOIN payment p
ON c.customer_id=p.customer_id
GROUP BY c.customer_id, first_name, last_name
ORDER BY avg(amount) DESC 
LIMIT 1;
```


